### ISSUE TITLE
Cannot load backend etcd: no such file to load -- hiera/backend/etcd_backend

### ISSUE THREAD

**Issue by kyleodonnell** [garethr/hiera-etcd#9]
im sure this is a problem with my general lack of puppet knowledge but nonetheless I am still scratching my head.  getting an error trying to query a hiera value, any ideas?

ii  hiera                       1.3.4-1puppetlabs1          A simple pluggable Hierarchical Database.
ii  puppet                      3.7.4-1puppetlabs1          Centralized configuration management - agent startup and compatibility

```
# cat /etc/hiera.yaml 

---
:backends:
  - yaml
  - etcd

:hierarchy:
  - defaults
  - "%{clientcert}"
  - "%{environment}"
  - global

:yaml:
# datadir is empty here, so hiera uses its defaults:
# - /var/lib/hiera on *nix
# - %CommonAppData%\PuppetLabs\hiera\var on Windows
# When specifying a datadir, make sure the directory exists.
  :datadir: /var/lib/hiera

:http:
  :host: 127.0.0.1
  :port: 4001
  :paths:
    - /
```

/x/i/bin/etcdctl get /foo
bar

```
 /usr/bin/hiera -d foo
WARN: Tue Mar 24 20:25:53 +0000 2015: Cannot load backend etcd: no such file to load -- hiera/backend/etcd_backend
DEBUG: Tue Mar 24 20:25:53 +0000 2015: Hiera YAML backend starting
DEBUG: Tue Mar 24 20:25:53 +0000 2015: Looking up foo in YAML backend
DEBUG: Tue Mar 24 20:25:53 +0000 2015: Looking for data source defaults
DEBUG: Tue Mar 24 20:25:53 +0000 2015: Cannot find datafile /var/lib/hiera/defaults.yaml, skipping
DEBUG: Tue Mar 24 20:25:53 +0000 2015: Looking for data source global
DEBUG: Tue Mar 24 20:25:53 +0000 2015: Cannot find datafile /var/lib/hiera/global.yaml, skipping
nil
```

**Comment by garethr** [comment]
Hi @kyleodonnell. Could I ask how you installed the backend? 

I think you're probably running into the issue described here: https://docs.puppetlabs.com/hiera/1/custom_backends.html#filenamepath

When used inside Puppet, Hiera will automatically load the backend. When using the hiera command line you'll need to explicitly set the RUBYLIB:

```
RUBYLIB=/etc/puppet/modules/hiera_etcd/lib hiera 
```

**Comment by kyleodonnell** [comment]
That looks to be problem...but onto the next!

I installed via puppet module install

/usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require': /var/lib/gems/1.8/gems/etcd-0.2.4/lib/etcd/client.rb:22: syntax error, unexpected '>' (SyntaxError)
    HTTP_REDIRECT = ->(r) { r.is_a? Net::HTTPRedirection }
                      ^
/var/lib/gems/1.8/gems/etcd-0.2.4/lib/etcd/client.rb:22: syntax error, unexpected '{', expecting kEND
    HTTP_REDIRECT = ->(r) { r.is_a? Net::HTTPRedirection }
                           ^
/var/lib/gems/1.8/gems/etcd-0.2.4/lib/etcd/client.rb:22: syntax error, unexpected '}', expecting kEND
/var/lib/gems/1.8/gems/etcd-0.2.4/lib/etcd/client.rb:23: syntax error, unexpected '>'
    HTTP_SUCCESS = ->(r) { r.is_a? Net::HTTPSuccess }
                     ^
/var/lib/gems/1.8/gems/etcd-0.2.4/lib/etcd/client.rb:23: syntax error, unexpected '{', expecting kEND
    HTTP_SUCCESS = ->(r) { r.is_a? Net::HTTPSuccess }
                          ^
/var/lib/gems/1.8/gems/etcd-0.2.4/lib/etcd/client.rb:23: syntax error, unexpected '}', expecting kEND
/var/lib/gems/1.8/gems/etcd-0.2.4/lib/etcd/client.rb:24: syntax error, unexpected '>'
    HTTP_CLIENT_ERROR = ->(r) { r.is_a? Net::HTTPClientError }
                          ^
/var/lib/gems/1.8/gems/etcd-0.2.4/lib/etcd/client.rb:24: syntax error, unexpected '{', expecting kEND
    HTTP_CLIENT_ERROR = ->(r) { r.is_a? Net::HTTPClientError }
                               ^
/var/lib/gems/1.8/gems/etcd-0.2.4/lib/etcd/client.rb:24: syntax error, unexpected '}', expecting kEND
/var/lib/gems/1.8/gems/etcd-0.2.4/lib/etcd/client.rb:142: syntax error, unexpected ':', expecting ')'
...ethod.downcase.to_sym, params: params)
                              ^
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in`require'
    from /var/lib/gems/1.8/gems/etcd-0.2.4/lib/etcd.rb:3
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:59:in `gem_original_require'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:59:in`require'
    from /etc/puppet/modules/hiera_etcd/lib/hiera/backend/etcd_backend.rb:7:in `initialize'
    from /var/lib/gems/1.8/gems/hiera-1.3.4/lib/hiera/backend.rb:205:in`new'
    from /var/lib/gems/1.8/gems/hiera-1.3.4/lib/hiera/backend.rb:205:in `lookup'
    from /var/lib/gems/1.8/gems/hiera-1.3.4/lib/hiera/backend.rb:203:in`each'
    from /var/lib/gems/1.8/gems/hiera-1.3.4/lib/hiera/backend.rb:203:in `lookup'
    from /var/lib/gems/1.8/gems/hiera-1.3.4/lib/hiera.rb:60:in`lookup'
    from /var/lib/gems/1.8/gems/hiera-1.3.4/bin/hiera:225
    from /usr/local/bin/hiera:19:in `load'
    from /usr/local/bin/hiera:19

**Comment by garethr** [comment]
@kyleodonnell I'm afraid it's very likely that the etcd client gem doesn't work with Ruby 1.8. It's certainly not tested on that version of ruby. https://github.com/ranjib/etcd-ruby/blob/master/.travis.yml

**Comment by kyleodonnell** [comment]
doh! 1.9+ required?

also thanks for responding!
